import {StatusBar} from 'expo-status-bar'
import React from 'react'
import {StyleSheet, Text, View} from 'react-native'

export default class MovementInfo extends React.Component {
  render() {
    return (
      <View style={styles.container}>
        <Text>THIS IS THE MOVEMENT INFO:</Text>
        <Text></Text>
        <Text>
        vwreviuyhbevpirvwervwervwieruvhwervvwreviuyhbevpirvwervwervwieruvhwervvwreviuyhbevpirvwervwervwieruvhwervvwreviuyhbevpirvwervwervwieruvhwervvwreviuyhbevpirvwervwervwieruvhwervvwreviuyhbevpirvwervwervwieruvhwervvwreviuyhbevpirvwervwervwieruvhwervvwreviuyhbevpirvwervwervwieruvhwervvwreviuyhbevpirvwervwervwieruvhwervvwreviuyhbevpirvwervwervwieruvhwervvwreviuyhbevpirvwervwervwieruvhwervvwreviuyhbevpirvwervwervwieruvhwervvwreviuyhbevpirvwervwervwieruvhwervvwreviuyhbevpirvwervwervwieruvhwervvwreviuyhbevpirvwervwervwieruvhwervvwreviuyhbevpirvwervwervwieruvhwervvwreviuyhbevpirvwervwervwieruvhwervvwreviuyhbevpirvwervwervwieruvhwervvwreviuyhbevpirvwervwervwieruvhwervvwreviuyhbevpirvwervwervwieruvhwervvwreviuyhbevpirvwervwervwieruvhwervvwreviuyhbevpirvwervwervwieruvhwervvwreviuyhbevpirvwervwervwieruvhwervvwreviuyhbevpirvwervwervwieruvhwervvwreviuyhbevpirvwervwervwieruvhwervvwreviuyhbevpirvwervwervwieruvhwervvwreviuyhbevpirvwervwervwieruvhwervvwreviuyhbevpirvwervwervwieruvhwervvwreviuyhbevpirvwervwervwieruvhwervvwreviuyhbevpirvwervwervwieruvhwervvwreviuyhbevpirvwervwervwieruvhwervvwreviuyhbevpirvwervwervwieruvhwervvwreviuyhbevpirvwervwervwieruvhwervvwreviuyhbevpirvwervwervwieruvhwervvwreviuyhbevpirvwervwervwieruvhwervvwreviuyhbevpirvwervwervwieruvhwervvwreviuyhbevpirvwervwervwieruvhwervvwreviuyhbevpirvwervwervwieruvhwervvwreviuyhbevpirvwervwervwieruvhwervvwreviuyhbevpirvwervwervwieruvhwervvwreviuyhbevpirvwervwervwieruvhwervvwreviuyhbevpirvwervwervwieruvhwervvwreviuyhbevpirvwervwervwieruvhwervvwreviuyhbevpirvwervwervwieruvhwervvwreviuyhbevpirvwervwervwieruvhwervvwreviuyhbevpirvwervwervwieruvhwervvwreviuyhbevpirvwervwervwieruvhwervvwreviuyhbevpirvwervwervwieruvhwervvwreviuyhbevpirvwervwervwieruvhwervvwreviuyhbevpirvwervwervwieruvhwervvwreviuyhbevpirvwervwervwieruvhwervv
        </Text>
        <StatusBar style="auto" />
      </View>
    );
  }
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#fff',
    alignItems: 'center',
    justifyContent: 'center'
  }
})
